### ISSUE TITLE
can you add an example for so wrap

### ISSUE THREAD

**Issue by Layty** [shybovycha/lua-bridge-sample#2]
hello,
 I have a cpp so with some class and shared_ptr,   and I want to use it in lua .

**Comment by shybovycha** [comment]
Hey,

Just got my hands on it. I do not know your exact situation, but I managed to make a sample for that.

Unfortunately, I could not figure out a simple way to expose STL containers and smart pointers to the Lua code - it is a library, so this would have to be done at compile time (unlike runtime, as LuaBridge is doing). Hence no `std::shared_ptr` or `std::vector` is getting converted to Lua tables automagically - you will have to do it yourself.

Anyways, see [`8-shared-library`](https://github.com/shybovycha/lua-bridge-sample/tree/master/8-shared-library) sample 👍
